languageCode = 'en-us'
languageName = "English"
weight = 1

title = "Clace : Web App Self-Hosting Made Easy"
copyright = "Copyright © 2023 ClaceIO, LLC"


[languages]
  [languages.en]
    [languages.en.params]
        displayName = "EN"
        isoCode = "en"
        rtl = false
        dateFormat = "2 January 2006"
        description = "Web App Self-Hosting Made Easy"

[params]
  mainSections = ["Features", "Docs", "Blog", "About"]

[params.author]
  name = "Clace"
  headline = "Web App Self-Hosting Made Easy"
  links = [
     { email = "mailto:contact@clace.io" },
     { github = "https://github.com/claceio" },
     { twitter = "https://twitter.com/claceio" },
     { linkedin = "https://www.linkedin.com/company/claceio"},
  ]
