languageCode = 'en-us'
languageName = "English"
weight = 1

title = "Clace : Easy Self-hosted Web Tools"
copyright = "Copyright © 2024 ClaceIO, LLC"


[languages]
  [languages.en]
    [languages.en.params]
        displayName = "EN"
        isoCode = "en"
        rtl = false
        dateFormat = "2 January 2006"
        description = "Easy Self-hosted Web Tools"

[params]
  mainSections = ["Features", "Docs", "Blog", "About"]

[params.author]
  name = "Clace"
  headline = "Easy Self-hosted Web Tools"
  links = [
     { email = "mailto:contact@clace.io" },
     { github = "https://github.com/claceio" },
     { twitter = "https://twitter.com/claceio" },
     # { linkedin = "https://www.linkedin.com/company/claceio"},
     { rss = "https://clace.io/blog/index.xml"},
     { discord = "https://discord.gg/t2P8pJFsd7"},
  ]
