languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Clace : Web App Self-Hosting Made Easy"
description = "Web App Self-Hosting Made Easy"
copyright = "Copyright © 2023 ClaceIO, LLC"

dateFormat = "2 January 2006"

[params]
  mainSections = ["Features", "Docs", "Blog", "About"]

[author]
  name = "CLACE"
  headline = "Web App Self-Hosting Made Easy"
  links = [
     { email = "mailto:contact@clace.io" },
     { github = "https://github.com/claceio" },
     { twitter = "https://twitter.com/claceio" },
     { linkedin = "https://www.linkedin.com/company/claceio"},
  ]
