baseURL = "https://clace.io/"
languageCode = "en-us"
title = "Clace"
canonifyURLs = false
relativeURLs = false
pluralizeListTitles = false
plainIdAnchors = true
defaultContentLanguage = "en"
enableInlineShortcodes = true

[[module.imports]]
path = 'github.com/imfing/hextra'

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.highlight]
noClasses = false

# Default Page Parameters
[params]
title = "Clace"
description = "Web App Deployment Platform"
image = "clace_icon.png"

[params.navbar]
displayTitle = false

[params.navbar.logo]
path = "clace.png"
width = 100
height = 100

[params.editurl]
enable = false
base = "https://github.com/claceio/docs/edit/main/content"

[params.footer]
displayCopyright = true
displayPoweredBy = false

[params.theme]
default = "system"
displayToggle = true

# Docs Navigation

[[menu.main]]
name = "QuickStart"
url = "/docs/quickstart"
identifier = "quickstart"
weight = 1

[[menu.main]]
name = "Docs"
url = "/docs"
identifier = "docs"
weight = 2

[[menu.main]]
name = "Blog"
url = "/blog"
identifier = "blog"
weight = 3

[[menu.main]]
name = "Search"
weight = 4
[menu.main.params]
type = "search"

[[menu.main]]
name = "GitHub"
weight = 5
url = "https://github.com/claceio/clace"
[menu.main.params]
icon = "github"

[[menu.sidebar]]
name = "More"
params.type = "separator"
weight = 1

[[menu.sidebar]]
name = "Demo"
url = "https://demo.clace.io"
